services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./tables.sql:/var/lib/postgresql/tables.sql
    environment:
      - POSTGRES_PASSWORD=ryd123
      - POSTGRES_USER=ryd
      - POSTGRES_DB=petrols
